name: scanxpert
description: A simple scanner application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #core
  easy_localization: ^3.0.2
  kartal: ^3.4.1
  equatable: ^2.0.5
  go_router: ^12.1.1

  #screen
  flutter_screenutil: ^5.9.0
  adaptive_theme: ^3.3.0
  flutter_svg: ^2.0.7
  flutter_spinkit: ^5.2.0

  #utils
  bot_toast: ^4.1.3
  keyboard_actions: ^4.2.0
  logger: ^2.0.2+1
  keyboard_dismisser: ^3.0.0

  #scanner
  # scan_plus: ^0.0.4

  #sign in
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.5
  crypto: ^3.0.3
  
  #google
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  google_fonts: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  build_runner: ^2.4.6

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/localizations/
    - assets/images/
    - assets/svg/
