// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUUbx4VZRsXftub1ba7H3a2e0jPwlAtSw',
    appId: '1:223057672216:android:53a3f55d33ef73a97c2b6d',
    messagingSenderId: '223057672216',
    projectId: 'scan-xpert',
    storageBucket: 'scan-xpert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqPsQtmsByQosNJuRAUhztISKfAwrvVyM',
    appId: '1:223057672216:ios:4421acdf9dcb29bf7c2b6d',
    messagingSenderId: '223057672216',
    projectId: 'scan-xpert',
    storageBucket: 'scan-xpert.appspot.com',
    androidClientId: '223057672216-kd3362u352cmprkd2kli2s769vv3i2a6.apps.googleusercontent.com',
    iosClientId: '223057672216-e2e8q6d0256334v4s6ji6m1mlmsl57vm.apps.googleusercontent.com',
    iosBundleId: 'com.mucoa.scanxpert',
  );
}
